on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependecies
        run: npm ci

      - name: Test application
        run: npm run test-ci

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependecies
        run: npm ci

      - name: Get current date
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get current and previous tags
        id: tags
        run: |
          echo "::set-output name=current::$(git tag -l --sort=-version:refname 'v*' | head -n 1)"
          echo "::set-output name=previous::$(git tag -l --sort=-version:refname 'v*' | head -n 2 | tail -n 1)"
        shell: bash

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          mytoken: ${{ secrets.GH_TOKEN }}
          head-ref: ${{ steps.tags.outputs.current }}
          base-ref: ${{ steps.tags.outputs.previous }}

      - name: Create release issue
        id: create_release_issue
        uses: JasonEtco/create-an-issue@v2
        env:
          VERSION: ${{ steps.tags.outputs.current }}
          AUTHOR: ${{ github.actor }}
          DATE: ${{ steps.date.outputs.date }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE.md
          update_existing: true
          search_existing: all

    outputs:
      issueNumber: ${{ steps.create_release_issue.outputs.number }}
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Release Author: ${{ github.actor }}
      #       Release Date: ${{steps.date.outputs.date}}
      #       Version: ${{ github.ref }}
      #       Changelog: ${{ steps.changelog.outputs.changelog }}
      #     draft: false
      #     prerelease: false

  gh-pages:
    name: gh-pages
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Cache deps
        uses: actions/cache@v3

        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependecies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Publish to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build

      - name: Comment issue with deploy
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ needs.release.outputs.issueNumber }}
          body: |
            Page link: https://myrrvinya.github.io/unit-demo-cra/
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ needs.release.outputs.issueNumber }}
          comment: |
            Issue automatically closed
